POST https://rtk-landmos.com:3000/api/getbystation
content-type: application/json

{
    "stat_code": "05"
}

###
GET https://rtk-landmos.com:3000/api/basestation


### 
GET http://localhost:3100/get_data

### 
GET http://localhost:3100/hello

###
POST https://engrids.soc.cmu.ac.th/p3500/api/insertdata
content-type: application/json

{
    "stname": "station_01", 
    "val_ec": 11, 
    "val_ph": 11, 
    "val_do": 11, 
    "val_tmp": 11
}

###
POST http://localhost:3500/api/selectdata
content-type: application/json

{
    "stat_code": "01", 
    "start_date": "2022-11-18", 
    "end_date": "2022-11-19"
}

###
GET http://localhost:3500/api/test
content-type: application/json

{
    "stat_code": "01", 
    "start_date": "2022-11-18", 
    "end_date": "2022-11-19"
}
 

###
POST http://localhost/api/selectmultidata
content-type: application/json

{
    "stat_code": ["01", "04"], 
    "start_date": "2022-11-18", 
    "end_date": "2022-11-19"
}

###
GET http://localhost/apiv2/basestation