POST https://rtk-landmos.com:3000/api/getbystation
content-type: application/json

{
    "stat_code": "05"
}

###
GET https://rtk-landmos.com:3000/api/basestation


### 
GET http://localhost:3100/get_data

### 
GET http://localhost:3100/hello