version: '3.3'
services:
  postgis:
    image: postgis/postgis
    container_name: rtk_postgis
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=gnss
    ports:
      - 5433:5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
  flask:
    container_name: rtk_flask
    build: ./flaskapi
    restart: always
    depends_on:
      - postgis
    volumes:
      - ./flaskapi:/app/flaskapi
    ports:
      - "3100:3100"
    command: bash -c "cd flaskapi && python3 app.py"

  nodejs:
    image: node
    container_name: rtk_nodejs
    working_dir: /app/nodejs
    restart: always
    depends_on:
      - postgis
    environment:
      - NODE_ENV=production
    volumes:
      - ./nodejs:/app/nodejs
    ports:
      - 80:3500
    command: bash -c "npm i && npm i -g nodemon && npm i -g pm2 && nodemon server.js"
  # react:
  #   container_name: rtk_webapp
  #   build: ./react/
  #   depends_on:
  #     - postgis
  #   environment:
  #     - NODE_ENV=production
  #   volumes:
  #     - ./react:/usr/src/app
  #   ports:
  #     - 3000:3000
