version: '3.3'
services:
  postgis:
    image: postgis/postgis
    container_name: rtk_postgis
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=geodb
    ports:
      - 5433:5432
    # volumes:
    #   - ./postgres/geodb.sql:/docker-entrypoint-initdb.d/geodb.sql
  python:
    container_name: rtk_pythonapi
    build: ./python_api/
    ports:
      - "8000:5000"
  redis:
    image: "redis:alpine"

  nodejs:
    image: node
    container_name: rtk_nodejs
    working_dir: /app/nodejs
    restart: always
    depends_on:
      - postgis
    environment:
      - NODE_ENV=production
    volumes:
      - ./nodejs:/app/nodejs
    ports:
      - 3000:3000
    command: bash -c "npm i && npm i -g nodemon && npm i -g pm2 && nodemon server.js"

  react:
    container_name: rtk_webapp
    build: ./react/
    depends_on:
      - postgis
    environment:
      - NODE_ENV=development
    volumes:
      - ./react:/usr/src/app
    ports:
      - 3500:3000
